package com.lianhua.company.model;

// Generated 2013-3-23 11:34:39 by Hibernate Tools 3.6.0

import java.util.Date;

import com.lianhua.code.model.Code;
import com.lianhua.common.model.BusinessData;
import com.lianhua.common.model.Operator;
import com.lianhua.contact.model.Contact;
import com.lianhua.declaration.model.Declaration;
import com.lianhua.user.model.User;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable,
		com.rootrip.platform.common.dao.Entity<Long>, BusinessData {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Long contactId;
	private Contact contact;
	private String code;
	private String name;
	private String product1;
	private String product2;
	private String product3;
	private Long categoryCode;
	private Code category;
	private Long registerCode;
	private Long accountingCode;
	private Long organizationCode;
	private Integer masterNum;
	private Integer bachelorNum;
	private Integer collegeNum;
	private Integer otherNum;
	private Integer employeeNum;
	private String principal;
	private String preparer;
	private String mobile;
	private Date signDate;
	private Byte approveState;
	private Byte state;
	private Byte operation;
	private Integer year;
	private boolean sample = false;
	private Long businessTypeCode;
	private boolean majorInquiry = false;
	private boolean confirmed = false;

	private Long operatorId;
	private Operator operator;

	private Long userId;
	private User user;

	private Declaration declaration;

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProduct1() {
		return this.product1;
	}

	public void setProduct1(String product1) {
		this.product1 = product1;
	}

	public String getProduct2() {
		return this.product2;
	}

	public void setProduct2(String product2) {
		this.product2 = product2;
	}

	public String getProduct3() {
		return this.product3;
	}

	public void setProduct3(String product3) {
		this.product3 = product3;
	}

	public Integer getMasterNum() {
		return this.masterNum;
	}

	public void setMasterNum(Integer masterNum) {
		this.masterNum = masterNum;
	}

	public Integer getBachelorNum() {
		return this.bachelorNum;
	}

	public void setBachelorNum(Integer bachelorNum) {
		this.bachelorNum = bachelorNum;
	}

	public Integer getCollegeNum() {
		return this.collegeNum;
	}

	public void setCollegeNum(Integer collegeNum) {
		this.collegeNum = collegeNum;
	}

	public Integer getOtherNum() {
		return this.otherNum;
	}

	public void setOtherNum(Integer otherNum) {
		this.otherNum = otherNum;
	}

	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public String getPreparer() {
		return this.preparer;
	}

	public void setPreparer(String preparer) {
		this.preparer = preparer;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public Byte getApproveState() {
		return this.approveState;
	}

	public void setApproveState(Byte approveState) {
		this.approveState = approveState;
	}

	public Byte getState() {
		return this.state;
	}

	public void setState(Byte state) {
		this.state = state;
	}

	public Byte getOperation() {
		return this.operation;
	}

	public void setOperation(Byte operation) {
		this.operation = operation;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getContactId() {
		return contactId;
	}

	public void setContactId(Long contactId) {
		this.contactId = contactId;
	}

	public Long getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(Long categoryCode) {
		this.categoryCode = categoryCode;
	}

	public void setRegisterCode(Long registerCode) {
		this.registerCode = registerCode;
	}

	public void setAccountingCode(Long accountingCode) {
		this.accountingCode = accountingCode;
	}

	public void setOrganizationCode(Long organizationCode) {
		this.organizationCode = organizationCode;
	}

	public Long getRegisterCode() {
		return registerCode;
	}

	public Long getAccountingCode() {
		return accountingCode;
	}

	public Long getOrganizationCode() {
		return organizationCode;
	}

	public Operator getOperator() {
		return operator;
	}

	public void setOperator(Operator operator) {
		this.operator = operator;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public boolean isSample() {
		return sample;
	}

	public void setSample(boolean sample) {
		this.sample = sample;
	}

	public Declaration getDeclaration() {
		return declaration;
	}

	public void setDeclaration(Declaration declaration) {
		this.declaration = declaration;
	}

	public Integer getEmployeeNum() {
		return employeeNum;
	}

	public void setEmployeeNum(Integer employeeNum) {
		this.employeeNum = employeeNum;
	}

	public Long getBusinessTypeCode() {
		return businessTypeCode;
	}

	public void setBusinessTypeCode(Long businessTypeCode) {
		this.businessTypeCode = businessTypeCode;
	}

	public Code getCategory() {
		return category;
	}

	public void setCategory(Code category) {
		this.category = category;
	}

	public boolean isMajorInquiry() {
		return majorInquiry;
	}

	public void setMajorInquiry(boolean majorInquiry) {
		this.majorInquiry = majorInquiry;
	}

	public boolean isConfirmed() {
		return confirmed;
	}

	public void setConfirmed(boolean confirmed) {
		this.confirmed = confirmed;
	}

}
