package com.lianhua.notice.model;

// Generated 2013-7-18 10:23:07 by Hibernate Tools 3.6.0

import java.util.Date;

import com.rootrip.platform.common.dao.Ordered;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable,
		com.rootrip.platform.common.dao.Entity<Long>, Ordered {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Long typeId;
	private NoticeType type;
	private String title;
	private String content;
	private boolean important = false;
	private boolean news = false;
	private long bySort;
	private Date addTime;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getTypeId() {
		return typeId;
	}
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}
	public NoticeType getType() {
		return type;
	}
	public void setType(NoticeType type) {
		this.type = type;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public boolean isImportant() {
		return important;
	}
	public void setImportant(boolean important) {
		this.important = important;
	}
	public boolean isNews() {
		return news;
	}
	public void setNews(boolean news) {
		this.news = news;
	}
	public long getBySort() {
		return bySort;
	}
	public void setBySort(long bySort) {
		this.bySort = bySort;
	}
	public Date getAddTime() {
		return addTime;
	}
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}


}
