package com.lianhua.notice.model;

// Generated 2013-7-18 10:23:07 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * PubLink generated by hbm2java
 */
public class PubLink implements java.io.Serializable,
		com.rootrip.platform.common.dao.Entity<Long> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private String title;
	private String url;
	private long bySort;
	private Date addTime;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public long getBySort() {
		return bySort;
	}
	public void setBySort(long bySort) {
		this.bySort = bySort;
	}
	public Date getAddTime() {
		return addTime;
	}
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}


}
