package com.lianhua.area.model;

import java.util.List;

// Generated 2013-3-12 9:17:45 by Hibernate Tools 3.6.0

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable,
		com.rootrip.platform.common.dao.Entity<Long>, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Byte level;
	private String name;
	private String ename;
	private String code;

	private Long parentId;
	private Area parent;
	private List<Area> children;

	public Byte getLevel() {
		return this.level;
	}

	public void setLevel(Byte level) {
		this.level = level;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Area getParent() {
		return parent;
	}

	public void setParent(Area parent) {
		this.parent = parent;
	}

	@Override
	public Object clone(){
		Area area = new Area();
		area.setId(id);
		area.setLevel(level);
		area.setName(name);
		area.setEname(ename);
		area.setCode(code);
		area.setParentId(parentId);
		area.setParent(parent);
		return area;
	}

	public List<Area> getChildren() {
		return children;
	}

	public void setChildren(List<Area> children) {
		this.children = children;
	}
}
