package com.lianhua.declaration.model;

import com.lianhua.common.model.BusinessData;
import com.lianhua.common.model.Operator;
import com.lianhua.company.model.Company;

// Generated 2013-3-27 13:37:50 by Hibernate Tools 3.6.0

/**
 * Approval generated by hbm2java
 */
public class Approval implements java.io.Serializable,
		com.rootrip.platform.common.dao.Entity<Long>, BusinessData {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private String state;
	private String step;
	private String comment;
	private Byte type;
	private String reason;

	private Operator operator;
	private Long declarationId;
	private Declaration declaration;
	private Long companyId;
	private Company company;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getStep() {
		return step;
	}
	public void setStep(String step) {
		this.step = step;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public Byte getType() {
		return type;
	}
	public void setType(Byte type) {
		this.type = type;
	}
	public String getReason() {
		return reason;
	}
	public void setReason(String reason) {
		this.reason = reason;
	}
	public Operator getOperator() {
		return operator;
	}
	public void setOperator(Operator operator) {
		this.operator = operator;
	}
	public Long getDeclarationId() {
		return declarationId;
	}
	public void setDeclarationId(Long declarationId) {
		this.declarationId = declarationId;
	}
	public Declaration getDeclaration() {
		return declaration;
	}
	public void setDeclaration(Declaration declaration) {
		this.declaration = declaration;
	}
	public Long getCompanyId() {
		return companyId;
	}
	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}
	public Company getCompany() {
		return company;
	}
	public void setCompany(Company company) {
		this.company = company;
	}
	

}
