package com.lianhua.declaration.model;

// Generated 2013-3-27 13:37:50 by Hibernate Tools 3.6.0

import com.lianhua.common.model.BusinessData;
import com.lianhua.common.model.Operator;
import com.lianhua.company.model.Company;

/**
 * Declaration generated by hbm2java
 */
public class Declaration implements java.io.Serializable,
		com.rootrip.platform.common.dao.Entity<Long>, BusinessData {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Byte state;
	private Integer year;
	
	private Long companyId;
	private Company company;
	private Operator operator;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Byte getState() {
		return state;
	}
	public void setState(Byte state) {
		this.state = state;
	}
	public Integer getYear() {
		return year;
	}
	public void setYear(Integer year) {
		this.year = year;
	}
	public Long getCompanyId() {
		return companyId;
	}
	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}
	public Company getCompany() {
		return company;
	}
	public void setCompany(Company company) {
		this.company = company;
	}
	public Operator getOperator() {
		return operator;
	}
	public void setOperator(Operator operator) {
		this.operator = operator;
	}


}
